name: build push image
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: surote/py-http-call:${{ github.sha }}

      -
        name: Build for Quay
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: py-http-call:${{ github.sha }}

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: py-http-call
          tags: py-http-call:${{ github.sha }}
          registry: quay.io/rh_ee_swongpai
          username: rh_ee_swongpai
          password: ${{ secrets.QUAY_SECRET }}